### PR TITLE
Aimee/python/lab03

### PR DESCRIPTION
**Pull request by aimeeny**

### CODE REVIEW

**Review by knizzle — CHANGES_REQUESTED** [review]
@aimeeny 

Hey Aimee! Looks good - just need add in your half-dollars.

**Comment by aimeeny** [comment]
@knizzle I'm only seeing half dollars in the optional version 2 - do I still need to add them in to version 1?

**Comment by knizzle** [comment]
@aimeeny 

Nope, my bad! I didn't know that v.2 was optional. You're good!

**Review by knizzle — APPROVED** [review]
@pjz987 

Version 1 is good to go. Version 2 was optional.

**Review by pjz987 — APPROVED** [review]

**Pull request merged**
