### PR TITLE
Aimee/javascript/pick3

### PR DESCRIPTION
**Pull request by aimeeny**

### CODE REVIEW

**Comment by knizzle** [comment]
Part A's complete; please wait until Part B's are done to merge this branch. 

-Kelsey, 5/12/22

**Review by knizzle — CHANGES_REQUESTED** [review]
Really, really close on the Blackjack/lab03 -- 

Take a look at where you are storing your variables; right now the user is getting '3 - hit!' every time.

**Comment by aimeeny** [comment]
@knizzle if you select new cards and then refresh, it should work fine. I'm able to get the correct values and result if I refresh

**Comment by knizzle** [comment]
> @knizzle if you select new cards and then refresh, it should work fine. I'm able to get the correct values and result if I refresh

Oh, interesting - that works haha. Might make it easier for the user to declare your variables _inside_ the function (that way it will grab the value after clicking the button), but no worries!

**Review by knizzle — APPROVED** [review]

**Review by knizzle — APPROVED** [review]

**Review by pjz987 — APPROVED** [review]

**Pull request merged**
